export { UserProfile } from './ui/profile/UserProfile'
export { UserPhone } from './ui/phone/UserPhone'
export { UserAddress } from './ui/address/UserAddress'
export type { IUserProfileProps } from './ui/profile/UserProfile'
export type { IUserPhoneProps } from './ui/phone/UserPhone'
export type { IUserAddressProps } from './ui/address/UserAddress'
export { UserProfileDlc } from './UserProfileDlc'
export { UserPhoneDlc } from './UserPhoneDlc'
export { UserAddressDlc } from './UserAddressDlc'