// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import ()

type Nationality struct {
	Code        int32  `json:"code"`
	Alpha2      string `json:"alpha_2"`
	Alpha3      string `json:"alpha_3"`
	Nationality string `json:"nationality"`
}
