// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"context"
)

type Querier interface {
	ListNationalities(ctx context.Context) ([]Nationality, error)
}

var _ Querier = (*Queries)(nil)
