// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type PassportFingerPrint struct {
	ID        uuid.UUID    `json:"id"`
	PublicKey string       `json:"public_key"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
