// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFingerPrint(ctx context.Context, publicKey string) (uuid.UUID, error)
	GetFingerPrint(ctx context.Context, id uuid.UUID) (PassportFingerPrint, error)
	UpdateFingerPrint(ctx context.Context, arg UpdateFingerPrintParams) error
}

var _ Querier = (*Queries)(nil)
