// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFingerPrint(ctx context.Context, publicKey string) (uuid.UUID, error)
	CreateRoleClass(ctx context.Context, class string) (string, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (uuid.UUID, error)
	CreateUserPassport(ctx context.Context, arg CreateUserPassportParams) (uuid.UUID, error)
	CreateUserPhone(ctx context.Context, arg CreateUserPhoneParams) (uuid.UUID, error)
	CreateUserPhoto(ctx context.Context, arg CreateUserPhotoParams) (uuid.UUID, error)
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (uuid.UUID, error)
	GetFingerPrint(ctx context.Context, id uuid.UUID) (PassportFingerPrint, error)
	GetRoleClass(ctx context.Context, class string) (RoleClass, error)
	GetUserAddress(ctx context.Context, id uuid.UUID) (UserAddress, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error)
	GetUserPassport(ctx context.Context, id uuid.UUID) (UserPassport, error)
	GetUserPhone(ctx context.Context, id uuid.UUID) (UserPhone, error)
	GetUserPhoneByNumberAndCode(ctx context.Context, arg GetUserPhoneByNumberAndCodeParams) (UserPhone, error)
	GetUserPhoto(ctx context.Context, id uuid.UUID) (UserPhoto, error)
	GetUserPhotoByFileName(ctx context.Context, fileName string) (UserPhoto, error)
	GetUserRole(ctx context.Context, id uuid.UUID) (UserRole, error)
	ListCountries(ctx context.Context) ([]Country, error)
	ListNationalities(ctx context.Context) ([]Nationality, error)
	ListRoleClasses(ctx context.Context) ([]RoleClass, error)
	ListUserSex(ctx context.Context) ([]string, error)
	SetAddressRelation(ctx context.Context, arg SetAddressRelationParams) error
	SetPhoneRelation(ctx context.Context, arg SetPhoneRelationParams) error
	SetPhotoRelation(ctx context.Context, arg SetPhotoRelationParams) error
	UpdateFingerPrint(ctx context.Context, arg UpdateFingerPrintParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) error
	UpdateUserPassport(ctx context.Context, arg UpdateUserPassportParams) error
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error
	UpdateUserPhoto(ctx context.Context, arg UpdateUserPhotoParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
