// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user_sex.sql

package db

import (
	"context"
)

const listUserSex = `-- name: ListUserSex :many
SELECT value FROM user_sex
ORDER BY "value"
`

func (q *Queries) ListUserSex(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserSex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
